/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTestimonialsRouteImport } from './routes/_admin.testimonials'
import { Route as AdminSiteVisitsRouteImport } from './routes/_admin.site-visits'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminProfileRouteImport } from './routes/_admin.profile'
import { Route as AdminOffersRouteImport } from './routes/_admin.offers'
import { Route as AdminMediaRouteImport } from './routes/_admin.media'
import { Route as AdminFaqRouteImport } from './routes/_admin.faq'
import { Route as AdminEnquiriesRouteImport } from './routes/_admin.enquiries'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/_admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/_admin.categories'
import { Route as AdminBlogsRouteImport } from './routes/_admin.blogs'
import { Route as AdminPropertiesIndexRouteImport } from './routes/_admin.properties.index'
import { Route as AdminPropertiesNewRouteImport } from './routes/_admin.properties.new'
import { Route as AdminPropertiesIdRouteImport } from './routes/_admin.properties.$id'
import { Route as AdminPropertiesIdEditRouteImport } from './routes/_admin.properties.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteVisitsRoute = AdminSiteVisitsRouteImport.update({
  id: '/site-visits',
  path: '/site-visits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesNewRoute = AdminPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesIdRoute = AdminPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesIdEditRoute = AdminPropertiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminPropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/blogs': typeof AdminBlogsRoute
  '/categories': typeof AdminCategoriesRoute
  '/customers': typeof AdminCustomersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/enquiries': typeof AdminEnquiriesRoute
  '/faq': typeof AdminFaqRoute
  '/media': typeof AdminMediaRoute
  '/offers': typeof AdminOffersRoute
  '/profile': typeof AdminProfileRoute
  '/settings': typeof AdminSettingsRoute
  '/site-visits': typeof AdminSiteVisitsRoute
  '/testimonials': typeof AdminTestimonialsRoute
  '/properties/$id': typeof AdminPropertiesIdRouteWithChildren
  '/properties/new': typeof AdminPropertiesNewRoute
  '/properties/': typeof AdminPropertiesIndexRoute
  '/properties/$id/edit': typeof AdminPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/blogs': typeof AdminBlogsRoute
  '/categories': typeof AdminCategoriesRoute
  '/customers': typeof AdminCustomersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/enquiries': typeof AdminEnquiriesRoute
  '/faq': typeof AdminFaqRoute
  '/media': typeof AdminMediaRoute
  '/offers': typeof AdminOffersRoute
  '/profile': typeof AdminProfileRoute
  '/settings': typeof AdminSettingsRoute
  '/site-visits': typeof AdminSiteVisitsRoute
  '/testimonials': typeof AdminTestimonialsRoute
  '/properties/$id': typeof AdminPropertiesIdRouteWithChildren
  '/properties/new': typeof AdminPropertiesNewRoute
  '/properties': typeof AdminPropertiesIndexRoute
  '/properties/$id/edit': typeof AdminPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_admin/blogs': typeof AdminBlogsRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/enquiries': typeof AdminEnquiriesRoute
  '/_admin/faq': typeof AdminFaqRoute
  '/_admin/media': typeof AdminMediaRoute
  '/_admin/offers': typeof AdminOffersRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/site-visits': typeof AdminSiteVisitsRoute
  '/_admin/testimonials': typeof AdminTestimonialsRoute
  '/_admin/properties/$id': typeof AdminPropertiesIdRouteWithChildren
  '/_admin/properties/new': typeof AdminPropertiesNewRoute
  '/_admin/properties/': typeof AdminPropertiesIndexRoute
  '/_admin/properties/$id/edit': typeof AdminPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/blogs'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/enquiries'
    | '/faq'
    | '/media'
    | '/offers'
    | '/profile'
    | '/settings'
    | '/site-visits'
    | '/testimonials'
    | '/properties/$id'
    | '/properties/new'
    | '/properties/'
    | '/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/blogs'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/enquiries'
    | '/faq'
    | '/media'
    | '/offers'
    | '/profile'
    | '/settings'
    | '/site-visits'
    | '/testimonials'
    | '/properties/$id'
    | '/properties/new'
    | '/properties'
    | '/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/forgot-password'
    | '/login'
    | '/_admin/blogs'
    | '/_admin/categories'
    | '/_admin/customers'
    | '/_admin/dashboard'
    | '/_admin/enquiries'
    | '/_admin/faq'
    | '/_admin/media'
    | '/_admin/offers'
    | '/_admin/profile'
    | '/_admin/settings'
    | '/_admin/site-visits'
    | '/_admin/testimonials'
    | '/_admin/properties/$id'
    | '/_admin/properties/new'
    | '/_admin/properties/'
    | '/_admin/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/testimonials': {
      id: '/_admin/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/site-visits': {
      id: '/_admin/site-visits'
      path: '/site-visits'
      fullPath: '/site-visits'
      preLoaderRoute: typeof AdminSiteVisitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/offers': {
      id: '/_admin/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/media': {
      id: '/_admin/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faq': {
      id: '/_admin/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/enquiries': {
      id: '/_admin/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blogs': {
      id: '/_admin/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/properties/': {
      id: '/_admin/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/properties/new': {
      id: '/_admin/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AdminPropertiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/properties/$id': {
      id: '/_admin/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AdminPropertiesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/properties/$id/edit': {
      id: '/_admin/properties/$id/edit'
      path: '/edit'
      fullPath: '/properties/$id/edit'
      preLoaderRoute: typeof AdminPropertiesIdEditRouteImport
      parentRoute: typeof AdminPropertiesIdRoute
    }
  }
}

interface AdminPropertiesIdRouteChildren {
  AdminPropertiesIdEditRoute: typeof AdminPropertiesIdEditRoute
}

const AdminPropertiesIdRouteChildren: AdminPropertiesIdRouteChildren = {
  AdminPropertiesIdEditRoute: AdminPropertiesIdEditRoute,
}

const AdminPropertiesIdRouteWithChildren =
  AdminPropertiesIdRoute._addFileChildren(AdminPropertiesIdRouteChildren)

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteVisitsRoute: typeof AdminSiteVisitsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminPropertiesIdRoute: typeof AdminPropertiesIdRouteWithChildren
  AdminPropertiesNewRoute: typeof AdminPropertiesNewRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteVisitsRoute: AdminSiteVisitsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminPropertiesIdRoute: AdminPropertiesIdRouteWithChildren,
  AdminPropertiesNewRoute: AdminPropertiesNewRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
